name: parse_color
description: A package that parses ints and strings (hex or rgba) into a color, with basic in-memory caching.
version: 0.0.1
homepage: https://github.com/camrongiuliani/parse_color

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
